apiVersion: apps/v1
kind: Deployment
metadata:
  name: creditcard
  namespace: crossell
spec:
  selector:
    matchLabels:
      app: creditcard
  replicas: 1
  template:
    metadata:
      labels:
        app: creditcard
    spec:      
      containers:
      - name: creditcard
        image: 483584640083.dkr.ecr.ap-south-1.amazonaws.com/creditcardportal-fe:#{appName}#-#{Build.BuildId}#.#{Build.DefinitionVersion}#PROD
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: creditcard
  namespace: crossell
  labels:
    app: creditcard
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: creditcard

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/strip-path: "true" 
  name: creditcard
  namespace: crossell
spec:
  tls:
  - hosts:
    - kotak811.com
    secretName: acqui-prod
  rules:
  - host: kotak811.com
    http:
      paths:
      - backend:
          service:
            name: creditcard
            port:
              number: 3000
        path: /creditcard
        pathType: Prefix
